# Generated by Django 5.0.4 on 2024-04-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
